# Generated by Django 2.2.13 on 2021-02-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210201_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='QjBD19dZ7NjZTD5Sa28C', max_length=20, unique=True),
        ),
    ]
