# Generated by Django 2.2.13 on 2021-02-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210201_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='2jVeFlf2AcSsNi9Yx1eD', max_length=20, unique=True),
        ),
    ]
