# Generated by Django 2.2.13 on 2021-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210206_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Sport'), ('C', 'Casual'), ('F', 'Formal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='pZIere86ItiGQMrG0wvS', max_length=20, unique=True),
        ),
    ]
