# Generated by Django 2.2.13 on 2021-02-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210207_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('B', 'bestseller')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='KVSxsxEwB5qa6TCsNzz6', max_length=20, unique=True),
        ),
    ]
