# Generated by Django 2.2.13 on 2021-02-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210208_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_pictures/thumbs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='4ar7FjeIe8uPvbkW9qe8', max_length=20, unique=True),
        ),
    ]
