# Generated by Django 2.2.13 on 2021-02-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210201_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'new'), ('B', 'bestseller')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='PvnAksovXFu5MmktJ4G7', max_length=20, unique=True),
        ),
    ]
