# Generated by Django 2.2.13 on 2021-02-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210207_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='adgDW9r4kfVCjbnyfQ44', max_length=20, unique=True),
        ),
    ]
