# Generated by Django 2.2.13 on 2021-02-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210208_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('B', 'bestseller'), ('BP', 'best price')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='Tmm0eKdIydq79lB7FokI', max_length=20, unique=True),
        ),
    ]
