# Generated by Django 2.2.13 on 2021-02-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210208_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='EyuszuXpm01r5xcRYpRT', max_length=20, unique=True),
        ),
    ]
