# Generated by Django 2.2.13 on 2021-02-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210216_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('B', 'bestseller'), ('BP', 'best price')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='WgKjeh0rK26A092Im33q', max_length=20, unique=True),
        ),
    ]
